FROM instedd/nginx-rails:1.9

RUN \
  apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y libzmq3-dev sox festival && \
  apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
