?METHOD_TPL(asterisk_config_dir).
?METHOD_TPL(asterisk_sounds_dir).
?METHOD_TPL(asterisk_record_dir).
?METHOD_TPL(broker_host).
?METHOD_TPL(broker_port).
?METHOD_TPL(broker_bind).
?METHOD_TPL(ami_host).
?METHOD_TPL(ami_port).
?METHOD_TPL(asterisk_agi_use_pipe_separator).
?METHOD_TPL(base_url).
?METHOD_TPL(record_dir).
?METHOD_TPL(seconds_between_calls).
?METHOD_TPL(seconds_for_call_back).
?METHOD_TPL(db_name).
?METHOD_TPL(db_user).
?METHOD_TPL(db_pass).
?METHOD_TPL(db_host).
?METHOD_TPL(crypt_secret).
?METHOD_TPL(nuntium_host).
?METHOD_TPL(nuntium_account).
?METHOD_TPL(nuntium_app).
?METHOD_TPL(nuntium_app_password).
?METHOD_TPL(guisso_client_id).
?METHOD_TPL(guisso_client_secret).
?METHOD_TPL(guisso_url).
?METHOD_TPL(broker_httpd_base_url).
?METHOD_TPL(twilio_callback_url).
?METHOD_TPL(twilio_base_url).
?METHOD_TPL(hub_enabled).
?METHOD_TPL(hub_url).

-undef(METHOD_TPL).
