#!/bin/bash

# Set rake command
RAKE_COMMAND="${RAKE_COMMAND:-rake}"

# Initialize database
$RAKE_COMMAND db:create;

# Schema load and seed if first run, migrate otherwise
if [ `$RAKE_COMMAND db:version | cut -f2 -d ':'` == 0 ];
  then $RAKE_COMMAND db:schema:load db:seed;
  else $RAKE_COMMAND db:migrate;
fi;
