name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set environment up
        run: |
          docker compose pull
          docker compose build
          docker compose run --rm broker sh -c './rebar get-deps'
          docker compose run --rm broker sh -c './rebar compile'
          docker compose run --rm web bundle install
          docker compose run --rm web rake db:setup
          docker compose run --rm web rake db:test:prepare

      - name: Run specs
        run: |
          docker compose run --rm web rspec
          docker compose run --rm broker make eunit

  build:
    needs: test
    runs-on: ubuntu-24.04
    env:
      DOCKER_REPOSITORY: 'instedd/verboice'
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
    steps:
      - uses: actions/checkout@v4
      - name: Build image & push to Docker Hub
        run: ./build.sh
